### ISSUE TITLE
Not getting added as reviewer

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#14384]
## Expected Behavior

As a `CODEOWNER` I would expect to be added as a reviewer

## Actual Behavior

I'm noticing that I don't get tagged as a reviewer for changes to the Azure DevOps plugin which I'm in the `CODEOWNERS` file for.

Here's a recent example: https://github.com/backstage/backstage/pull/14353

Here's the current `CODEOWNERS` file: https://github.com/backstage/backstage/blob/158cd72bcdca5d95535d2dbcc8064d3686471592/.github/CODEOWNERS#L24

## Steps to Reproduce

1. Create a Pull Request with changes to `\plugins\auzre-devops`, `\plugins\auzre-devops-backend`, or `\plugins\auzre-devops-common`

Notice that `awanlin` is not added as a Reviewer, neither is `marleypowell` 

## Context

This would make things easier to review, right now I catch them in the `#bot` channel on Discord

## Your Environment

This isn't really an environment related issue

**Comment by kuangp** [comment]
hm I also recently noticed this too on a [PR](https://github.com/backstage/backstage/pull/13905/files) that modified some files from the playlist plugin that I'm listed as a codeowner. 

According to the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners): 

> The people you choose as code owners must have write permissions for the repository. 

which is probably not an option for non-maintainers 😕 I also found an open [enhancement request](https://github.com/orgs/community/discussions/23042) for this to work without write perms. Also found this [comment](https://github.com/renovatebot/renovate/issues/7927#issuecomment-908183630) which describes why this requirement exists. 

Perhaps we need to go with a GitHub Action instead of relying on CODEOWNERS here. Here are some I found which may accomplish what we want:
- https://github.com/marketplace/actions/add-pull-request-reviewer
- https://github.com/marketplace/actions/auto-request-review
- https://github.com/marketplace/actions/auto-assign-reviewer-by-files

**Comment by awanlin** [comment]
Interesting, thanks for adding on to this. I for sure don't expect write access.

**Comment by jhaals** [comment]
Thanks for pointing this out alongside the additional information! You're both awesome 🏅 Back from vacation now so I'll take a look at what we can do :)

**Comment by pjungermann** [comment]
I've recognized this, too.

https://github.com/backstage/backstage/blob/master/.github/CODEOWNERS even says that it contains errors  like
```
Unknown owner on line 19: make sure @kuangp exists and has write access to the repository
…         @backstage/reviewers @kuangp
```

**Comment by jhaals** [comment]
This will likely be fixed by #15317

**Comment by awanlin** [comment]
@jhaals, yes, that makes sense to me. Going to close this in the mean time

**Comment by thatwonguy** [comment]
I am getting similar issues. I have my own personal repos where I apply a rule that code owners should review any pull request before a merge to main branch can occur. I am in the code owners file for the repos but still unable to select my own username as reviewer, which forces me to simply bypass the ruleset to carry on with the merge.

Am I seeing this because I cannot review my own work or?
