### ISSUE TITLE
🐛 Bug Report: host property error when having extra path 

### ISSUE THREAD

**Issue by antoniobergas** [backstage/backstage#15996]
### 📜 Description

According to the backstage documentation it is compatible to point to a self service instance of azure devops server on the host property of the azure integration. However by having an extra path after the host and before the project, the integration does not work correctly.

### 👍 Expected behavior

Accept as host the entire url passed through the host property instead of subdividing the url and concatenating it with slashes, then any host url constructs in onpremise instance of azure devops server will work correctly.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/26031467/214958640-241f1c35-b7bc-4f41-a9f6-ce022cf84fba.png)
![image](https://user-images.githubusercontent.com/26031467/214958877-8bc8091c-94d0-4f66-a0db-0d01974932df.png)

The integration with the azure devops server onpremise instance doesnt work properly

### 👟 Reproduction steps

1. Add a host property in azure devops integration with extra path
2. Run backstage locally
3. The integration will fail

### 📃 Provide the context for the Bug.

The context is connect backstage to an onpremise azure devops server instance as the documentation mention

### 🖥️ Your Environment

OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v16.18.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3, 0.9.5
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-azure-devops-backend           0.3.20
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.5
  @backstage/plugin-catalog-backend-module-azure   0.1.12
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @antoniobergas, can you please try changing the `host:` value in your config to exclude the `https://` scheme? I'm wondering if that's the actual problem. It's not sure clear that this value is not supposed to be a full URL.

I remember helping some one with this exact problem. The issue in that case is here: https://github.com/backstage/backstage/issues/11679 and was fixed with this PR: https://github.com/backstage/backstage/pull/11701. The only difference I can tell between what you've done and what they have is the fact that you are including the `https://` scheme

**Comment by awanlin** [comment]
Hi @antoniobergas, did my suggestion above work? Can we close this issue?

**Comment by antoniobergas** [comment]
Hi @awanlin, yes I tried and at least it looks like is connecting to the server. Still have some permissions issues to access the catalog but I think is not related to backstage. 

Thanks a lot for the help!

**Comment by awanlin** [comment]
Awesome! Glad you've got it working @antoniobergas, good luck!
