### ISSUE TITLE
🐛 Bug Report: Errors when viewing AsyncAPI definition in HTML format 

### ISSUE THREAD

**Issue by borzoj** [backstage/backstage#17741]
### 📜 Description

When I add an API with definition using AsyncAPI standard, and try to view the API in the portal, the HTML view of the AsyncAPI documentation is not shown. Instead an error `Error: Version 2.0.0 is not supported.` is shown.

### 👍 Expected behavior

"Pretty" API documentation like this should be shown:
https://demo.backstage.io/catalog/default/api/streetlights/definition

### 👎 Actual Behavior with Screenshots

An error message is shown
![image](https://github.com/backstage/backstage/assets/6280685/aa463486-98a7-4158-8436-913b7521df29)

### 👟 Reproduction steps

1. Create a new backstage project: `npx @backstage/create-app backstage-test`
2. in `app-config.yaml` add the same API definition which is used in demo.backstage.io project:
```
  locations:
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml
```
3. run Backstage: `yarn dev`

### 📃 Provide the context for the Bug.

This happens when I create a new project using `npx @backstage/create-app backstage-test` even with the Streetlights API example used in demo Backstage project. If I checkout the demo project and run that, the documentation is shown correctly.

### 🖥️ Your Environment

```
yarn run v1.22.19
$ /private/var/dev/playground/backstage-test/node_modules/.bin/backstage-cli info
OS:   Darwin 22.2.0 - darwin/arm64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.6 (installed)
backstage:  1.13.0

Dependencies:
  @backstage/app-defaults                          1.3.0
  @backstage/backend-app-api                       0.4.2
  @backstage/backend-common                        0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.1
  @backstage/backend-tasks                         0.5.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.6
  @backstage/config-loader                         1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.7.0
  @backstage/core-components                       0.13.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.12
  @backstage/integration                           1.4.4
  @backstage/plugin-api-docs                       0.9.2
  @backstage/plugin-app-backend                    0.3.44
  @backstage/plugin-auth-backend                   0.18.2
  @backstage/plugin-auth-node                      0.2.13
  @backstage/plugin-catalog-backend                1.9.0
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.29
  @backstage/plugin-catalog-import                 0.9.7
  @backstage/plugin-catalog-node                   1.3.5
  @backstage/plugin-catalog-react                  1.5.0
  @backstage/plugin-catalog                        1.10.0
  @backstage/plugin-github-actions                 0.5.17
  @backstage/plugin-org                            0.6.7
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.7
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.38
  @backstage/plugin-scaffolder-backend             1.13.1
  @backstage/plugin-scaffolder-common              1.2.7
  @backstage/plugin-scaffolder-node                0.1.2
  @backstage/plugin-scaffolder-react               1.3.0
  @backstage/plugin-scaffolder                     1.13.0
  @backstage/plugin-search-backend-module-catalog  0.1.0
  @backstage/plugin-search-backend-module-pg       0.5.5
  @backstage/plugin-search-backend-module-techdocs 0.1.0
  @backstage/plugin-search-backend-node            1.2.0
  @backstage/plugin-search-backend                 1.3.0
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.5.2
  @backstage/plugin-search                         1.2.0
  @backstage/plugin-tech-radar                     0.6.3
  @backstage/plugin-techdocs-backend               1.6.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.12
  @backstage/plugin-techdocs-node                  1.7.0
  @backstage/plugin-techdocs-react                 1.1.5
  @backstage/plugin-techdocs                       1.6.1
  @backstage/plugin-user-settings                  0.7.2
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.0
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by borzoj** [comment]
Found the cause. My project created with `npx` included `@asyncapi/specs` package v.4.3.0 which is broken:
https://github.com/asyncapi/spec-json-schemas/releases/tag/v4.3.0

The first solution which worked for me was to force resolution of this package version to 4.1.1 in package.json:
```
"resolutions": {
    ...,
    "@asyncapi/specs": "4.1.1"
  },
```

It looks like if I recreate the project using npx it pulls @asyncapi/specs v.4.3.1 which is fixed.

**Comment by alexef** [comment]
I have @asyncapi/specs pinned at 4.1.1 but I still get the error that "version 2.0.0 is not supported". any other hints?
