### ISSUE TITLE
🐛 Bug Report: Highlighting library conflict leads to empty payload

### ISSUE THREAD

**Issue by dschwank** [backstage/backstage#18533]
### 📜 Description

Once you open the `raw` tab of the AsyncAPI definition widget and switch back to the AsyncApi, you can't see any `payload` examples anymore (see reproduction steps & screenshots).

The reason for that are two conflicting highlighting libraries. Right now two (or even more) different highlighting libraries are used within backstage directly or within a dependency.

The well known [highlight.js](https://github.com/highlightjs/highlight.js) library is used within backstage directly and in [asyncapi](https://github.com/asyncapi/asyncapi-react). It uses a global object for the configuration. So far so good (or not) ...

The problem is, that backstage also uses the [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) within the [CodeSnippet](https://github.com/backstage/backstage/blob/28ae2adcddd395c462c0dc101cc8b0a1e257d777/packages/core-components/src/components/CodeSnippet/CodeSnippet.tsx#L92) component, which internally uses the `highlight.js` extension [lowlight](https://github.com/wooorm/lowlight).

Lowlight changes the global `highlight.js` object, which causes `highlight.js` to return an empty string. See also: https://github.com/wooorm/lowlight/issues/47

### 👍 Expected behavior

- they payload examples are working within the AsyncAPI preview
- syntax highlighting works in all cases

<img width="534" alt="Bildschirmfoto 2023-07-04 um 11 19 36" src="https://github.com/backstage/backstage/assets/8232196/df1c9f14-22d7-4f3b-92b4-bd4ca120cb29">

### 👎 Actual Behavior with Screenshots

After switching _once_ to any page using the `CodeSnippet` component, the `highlight.js` library does not work anymore - and the payload of the AsyncAPI examples is always empty.

<img width="534" alt="Bildschirmfoto 2023-07-04 um 11 19 06" src="https://github.com/backstage/backstage/assets/8232196/4fd78282-4571-4a9f-b6bc-8860db612491">

### 👟 Reproduction steps

1. Go to <https://demo.backstage.io/catalog/default/api/streetlights/definition>
2. Click on the `Payload` button in the right panel _(=> you should see the example)_
3. Switch to the `raw` tab
4. Switch back to the `AsyncAPI` tab
5. Click on the `Payload` button in the right panel _(=> you should see an EMPTY example)_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dschwank** [comment]
To start a discussion about solutions:

1. we could either fix this issue https://github.com/wooorm/lowlight/issues/47
2. we replace the `react-syntax-highlighter` of the `CodeSnippet` component

Right now I tend to option (2) - replace the `react-syntax-highlighter`.

What are you ideas / thoughts?

**Comment by benjdlambert** [comment]
Looks like you're already fixing the issue @dschwank :tada: https://github.com/wooorm/lowlight/pull/51

Let's see what comes of that and see if we can just upgrade the library rather than switching out for something else just yet.

**Comment by dschwank** [comment]
Right 👍 I wasn't aware that `highlight.js` already [made a fix for that](https://github.com/wooorm/lowlight/issues/47#issuecomment-1620501793). So hopefully we can just update the `lowlight` version soon, and we are good to go 🥳

**Comment by dschwank** [comment]
The fix was merged and released yesterday. Will create a PR to upgrade the version of lowlight!

**Comment by ajax-kovtunov-o** [comment]
This problem still actual

**Comment by GregoryVds** [comment]
This is also very much a problem for us, unfortunately we don't have knowledge in the team today to work on this.

**Comment by pbronneberg** [comment]
Issue is still in. Can this issue be re-opened? Even if no-one is available to work on it, it remains an open issue

**Comment by benjdlambert** [comment]
Re-opened, if someone has time to work on this would be very much appreciated :pray:

**Comment by sumurzakov** [comment]
Hi @dschwank, I am new to Backstage. How have you fixed it ? Could you please explain or share some details about your workaround ?

**Comment by kushalshah5** [comment]
The issue still persists. Has anyone found a workaround yet?
