### ISSUE TITLE
🐛 Bug Report: Getting an error when creating a new project

### ISSUE THREAD

**Issue by RaphaelSve** [backstage/backstage#24941]
### 📜 Description

Installation with **`npx @backstage/create-app@latest`** failed

### 👍 Expected behavior

It should complete the installation

### 👎 Actual Behavior with Screenshots

When I run the command **`npx @backstage/create-app@latest`**, I get:

```
executing     yarn install ✖
Error: Could not execute command yarn install
```

Then I reran a **`yarn install`** where I got this error:

```
error /Users/abcde/Desktop/backstage/node_modules/@swc/core: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments:
Directory: /Users/abcde/Desktop/backstage/node_modules/@swc/core
Output:
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '/Users/abcde/Desktop/backstage/node_modules/@swc/core/postinstall.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### 👟 Reproduction steps

1 - `npx @backstage/create-app@latest`
2 - `yarn install`

### 🖥️ Your Environment

Windows 10 & macOS 14.5 yield the same result

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @RaphaelSve, can you share what version of node and yarn you are using? Just want to be able to test with the same setup. I ran this last week without any issues.

But I'm wondering if you are hitting this issue: https://github.com/swc-project/swc/issues/8988. Which has just been fixed in the last few hours. Can you try creating a new project and let me know if it just works this time around, please?

**Comment by RaphaelSve** [comment]
Hi @awanlin,

Indeed, it's been working again for a few hours

The project is functional on Node 20.12.2 (Windows) and 20.13.1 (macOS).

I am using Yarn version 1.22.22.

**Comment by UDtorrey** [comment]
Another data point FWIW - in case it helps someone else in the future.

I had problems with different yarn version and node versions.  
yarn version unknown (didnt check)
node version 20.14.0
nvm version 0.39.1 (nvm version shouldnt matter).
the above combination generated similar error's as OP when running `yarn dev` - webpack would not compile with `[0] Error: Cannot find module '@swc/types'`

`yarn upgrade` and the below combination, `yarn dev` was successful and `webpack compiled successfully` and 
yarn 1.22.19
nvm 0.39.1
node v20.13.1

**Comment by awanlin** [comment]
Thanks @UDtorrey, make sense as SWC had a bad release - https://github.com/swc-project/swc/issues/8988 - which then got fix fairly quickly. 👍

**Comment by ack81** [comment]
@awanlin this issue still exists. @backstage/create-app@latest will complete successfully but during a yarn build:backend it fails. 
I do not see the missing module in an of the package.json files.

`root@bc2468916414:/app# grep -i 'swc/types' package.json
root@bc2468916414:/app# grep -i 'swc/types' packages/backend/package.json
root@bc2468916414:/app# grep -i 'swc/types' packages/app/package.json`

`8.486 app:  Error: Failed to compile './src/index.tsx':
8.486 app:    Error: Cannot find module '@swc/types'
8.486 app:  Require stack:
8.486 app:  - /app/node_modules/@swc/core/index.js
8.486 app:  - /app/node_modules/swc-loader/src/index.js
8.486 app:  - /app/node_modules/loader-runner/lib/loadLoader.js
8.486 app:  - /app/node_modules/loader-runner/lib/LoaderRunner.js
8.486 app:  - /app/node_modules/webpack/lib/NormalModule.js
8.486 app:  - /app/node_modules/webpack/lib/ModuleFilenameHelpers.js
8.486 app:  - /app/node_modules/esbuild-loader/dist/index.cjs
8.486 app:  - /app/node_modules/@backstage/cli/dist/cjs/packageDetection-DT09yDE6.cjs.js
8.486 app:  - /app/node_modules/@backstage/cli/dist/cjs/buildBackend-FV4cZ7YT.cjs.js
8.486 app:  - /app/node_modules/@backstage/cli/dist/cjs/index-DtxQfUmH.cjs.js
8.486 app:  - /app/node_modules/@backstage/cli/dist/cjs/index-CS6xQRSZ.cjs.js
8.486 app:  - /app/node_modules/@backstage/cli/dist/index.cjs.js
8.486 app:  - /app/node_modules/@backstage/cli/bin/backstage-cli`


`npx @backstage/create-app --version   ->  1.27.0'
`yarn -v  ->  1.22.22`
`node -v  ->  v20.14.0`

**Comment by awanlin** [comment]
Hi @ack81, I can't reproduce this. It works for me with a fresh run of `npx @backstage/create-app@latest`.

You'll find that `grep` isn't terribly helpful as it won't walk the dependency tree. Can you share the output from `yarn why @swc/core`, please? I'm wondering if the old version is still getting pulled in for some reason 🤔

**Comment by sam-cogan** [comment]
I'm getting this issue as well, output from yarn why below:

`yarn why v1.22.22
[1/4] Why do we have the module "@swc/core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@swc/core@1.5.6"
info Reasons this module exists
   - "_project_#@backstage#cli" depends on it
   - Hoisted from "_project_#@backstage#cli#@swc#core"
info Disk size without dependencies: "248KB"
info Disk size with unique dependencies: "248KB"
info Disk size with transitive dependencies: "248KB"
info Number of shared dependencies: 2
Done in 1.60s.`

**Comment by awanlin** [comment]
Ok, @sam-cogan can you try creating a new instance in a different location just to see if you still have the issue?

**Comment by awanlin** [comment]
Might have spotted something that could help on this. I'm on Node 20 and I've just been running `yarn dev` as my validation. I spotted on Discord someone said they saw the issue running `yarn workspace backend build`. I still don't have the issue but I did see that for Node 18 there was a CI error here: https://github.com/backstage/backstage/actions/runs/9347932611/job/25725975828#step:8:27

**Comment by awanlin** [comment]
Sadly using Node 18 `yarn dev` and `yarn workspace backend build` both work for me 🤔

**Comment by sam-cogan** [comment]
Unfortunately creating a new instance in a different location has the same error, as does using `yarn workspace backend build`

**Comment by sam-cogan** [comment]
So running `yarn backstage-cli versions:bump` to bump the version to 1.27.6 seems to get rid of this error, and generate a new one:

```
0] ERROR in node:url
[0] Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
[0] Webpack supports "data:" and "file:" URIs by default.
[0] You may need an additional plugin to handle "node:" URIs.
[0]     at /c/repos/backstage-poc/backstage/node_modules/webpack/lib/NormalModule.js:918:25
[0]     at Hook.eval [as callAsync] (eval at create (/c/repos/backstage-poc/backstage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
[0]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/c/repos/backstage-poc/backstage/node_modules/tapable/lib/Hook.js:18:14)
[0]     at Object.processResource (/c/repos/backstage-poc/backstage/node_modules/webpack/lib/NormalModule.js:915:8)
[0]     at processResource (/c/repos/backstage-poc/backstage/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
[0]     at iteratePitchingLoaders (/c/repos/backstage-poc/backstage/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
[0]     at runLoaders (/c/repos/backstage-poc/backstage/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
[0]     at NormalModule._doBuild (/c/repos/backstage-poc/backstage/node_modules/webpack/lib/NormalModule.js:905:3)
[0]     at NormalModule.build (/c/repos/backstage-poc/backstage/node_modules/webpack/lib/NormalModule.js:1081:15)
[0]     at /c/repos/backstage-poc/backstage/node_modules/webpack/lib/Compilation.js:1400:12
[0]
```

**Comment by octaviobffernandes** [comment]
Experiencing the same as @sam-cogan

**Comment by sam-cogan** [comment]
If #25049 has been closed in favour of this bug, then this one should not be closed
