### ISSUE TITLE
🚀 Feature: Add autocompletion from github to the repourlpicker

### ISSUE THREAD

**Issue by GersonTf** [backstage/backstage#27884]
### 🔖 Feature description

Similar to https://github.com/backstage/backstage/pull/27367#issuecomment-2480083403 for gitlab
and https://github.com/backstage/backstage/pull/25132#issuecomment-2258270240 for bitbucket

It would be nice to also support github autocompletion of repos for the scaffolder.

I am creating the issue to notify that I want to work on this but I need to do more research before adding a better description, I will update this description in the future.

CC @benjdlambert I am tagging you since I see you involved in both the bitlab and bitbucket issue, this is my first time contributing so any support will be appreciated =) 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
@GersonTf I think the reason the bitbucket common module exists is because of the shared code between bitbucket server and bitbucket cloud. You don't have to create another module for this, I think it's fine to add to the existing github module for the scaffolder backend :tada:

**Comment by GersonTf** [comment]
Hi @benjdlambert @Rugvip 

I am already working on this and I am close to an implementation but I have a question. I see that the gitlab implementation is leveraging API calls to this [library](https://github.com/jdalrymple/gitbeaker)` import { Gitlab, GroupSchema } from '@gitbeaker/rest';`

After research, I found a similar library for [github](https://github.com/octokit/rest.js) called oktokit/rest. 
Would it be OK for me to use it on backstage?

**Comment by benjdlambert** [comment]
I think it's most likely that theres duplicates of the `octokit` library. I would look at the current version that's being used in the scaffolder github module. I don't think you'll need to install any more libraries, as the existing ones in the module should be enough.

I'd also look into copying a lot of the logic from something like the `github:repo:create` module which I think has some special management for the tokens.

https://github.com/backstage/backstage/blob/8743beff4d843cc0fe0896a04407369f2db5c902/plugins/scaffolder-backend-module-github/src/actions/githubRepoCreate.ts#L180-L186

**Comment by benjidotsh** [comment]
@GersonTf are you still working on this? We also want this functionality and if not, I don't mind taking over the work. 😄

**Comment by benjdlambert** [comment]
Closing as this has been fixed by the amazing work of @benjidotsh :tada:

**Comment by jaimewukb** [comment]
Hi all thanks for implementing this feature. Any ideas what i'm doing wrong when setting this up?

I've followed the release notes and done the following "This can be enabled by installing the @backstage/plugin-scaffolder-backend-module-github and configuring the [GitHub Auth Provider](https://backstage.io/docs/auth/github/provider/)." 

But for some reason i'm still getting this error in the networks tab. Any help would be appreciated!
![Image](https://github.com/user-attachments/assets/8313f531-9ce2-493c-b067-8f8cb5ab5a49)
