### ISSUE TITLE
Allow catalog entity refresh

### ISSUE THREAD

**Issue by novellat** [backstage/backstage#30503]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
refresh entity catalog
```

### 🗃️ Project Area

Catalog

### 🔖 Need

as we're updating entities in the catalog, sometimes it's useful to have a quick refresh instead of having to wait for a few minutes

### 📝 Proposal

<img width="511" height="267" alt="Image" src="https://github.com/user-attachments/assets/d7dec9ec-2172-4e06-a211-50dfdc4ed881" />

maybe for each row in the catalog entity search we could have a button for "refresh" of a given entity

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, and I have enough information to get started

**Comment by MihaiTabara** [comment]
Found in triaging this morning.

@novellat  thanks for filing this - just to clarify, to make sure I follow - you mean "refresh" an entity upon updating its contents in source control or something else?

**Comment by novellat** [comment]
@MihaiTabara yes, exactly

**Comment by andrei-ivanovici** [comment]
Unless I'm missing something, the feature is already  present. If you open a component you'll see a refresh button

<img width="1672" height="837" alt="Image" src="https://github.com/user-attachments/assets/ad341f21-df2d-4021-99b3-ea00fa705d4e" />

Click that and the component gets updated from the source.

**Comment by novellat** [comment]
@andrei-ivanovici the problem is with customized components when people overwrite this default behavior. So in this case it would be best to at least move the refresh button under the three dot menu on the top right of the screen.

**Comment by andrei-ivanovici** [comment]
Hi @novellat,  
  Thanks for clarifying this.   I don't see an issue with  the  option being available unde the 3 dots menu too :

<img width="1082" height="707" alt="Image" src="https://github.com/user-attachments/assets/c9500466-01ad-4dc7-8972-7bf69423729c" />

In the meantime, If you have custom components you can use the  API directly  and add whatever custom element makes sense in your use-case to trigger the refresh

**Comment by novellat** [comment]
Shall I create a PR?

**Comment by andrei-ivanovici** [comment]
I'd love this feature !

**Comment by novellat** [comment]
https://github.com/backstage/backstage/pull/30713/files implemented here

**Comment by awanlin** [comment]
I'm not sure I agree with this, for someone net new to Backstage who is using it as part of their day to day having this hidden in the context menu is not terribly intuitive.

For those who have chosen to hide this from the About card for their specific reasons I do support making it possible to add items to the context menu as a solution here. And with use moving along with the New Frontend System there is support for that by using the `EntityContextMenuItemBlueprint` more details here: https://github.com/backstage/backstage/pull/29515

**Comment by novellat** [comment]
@awanlin I think I copmletely understand you. Let me share my reasoning I used when implementing it:

- The "Refresh Entity" action is a convenience feature—helpful, but not essential. It fits well alongside other contextual actions already in the menu.

- It's also a safe operation that can't break anything, making it a low-risk addition.

- Regarding the comment about users choosing to hide it: in practice, most teams end up replacing the entire "About" card when customizing the page layout, often because it doesn’t provide enough value in their context. So the refresh button disappears as a side effect—not by deliberate exclusion.

I've implemented it mainly for our team, but might be useful for others.

**Comment by awanlin** [comment]
I still don't think that makes sense:

- The context of each potential adopter and their stages of adoption will greatly play into how useful the refresh is. For you it's not important for others it might be part of their flow. If I'm brand new to Backstage and I see it right on the About card why would I ever look for it in the context menu?
- It's duplication of code without clear reasons for it to be duplicate. I'm not very dogmatic about being DRY but this does seem like a case where avoiding duplication makes sense.
- Again, that might be in your context and is valid for you, would be great to hear more about the data driving your thinking? I'm basing my comments from the fact I've been helping people on Discord for a number of years and work with Backstage adopters day to day. You'd be surprised that a lot of people don't change this card. Those that do generally fork it and work from there. Forking is a bit of tribal knowledge, if you look on Discord that's what you'll see recommended. My hope is that post-New Frontend System we'll be able to pick up work to make this card easier to extend out of the box without needing to fork it.

At its heart Backstage should come with opinionated defaults but be open for customization. Adding to the context menu is something you can do today and gets easier with the New Frontend System.

As I mentioned in my PR review, if the Catalog Maintainers approve the change then I'm fine with that. Just wanting to note my thinking.
