### ISSUE TITLE
Introduce easy interfaces and hooks to get entities based on relationships

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#3655]
Since the relationships are in place, the need to query or filter entities based on relations emerges (see #3479, #3625). There are already some hooks that are siloed inside of individual plugins and can't be reused by others:
* [`isOwnerOf` @ catalog](https://github.com/backstage/backstage/blob/9a2a925716bbe38c2cea753ec2ef0ee17e7a0263/plugins/catalog/src/components/isOwnerOf.ts)
* [`getEntityRelations` @ catalog](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/getEntityRelations.ts)
* [`useRelatedEntities` @ api-docs](https://github.com/backstage/backstage/blob/9a2a925716bbe38c2cea753ec2ef0ee17e7a0263/plugins/api-docs/src/components/useRelatedEntities.ts)

## Feature Suggestion

I can image different use-cases for a first batch of reusable functions/hooks with a well-defined interface:
* ”I have two `EntityName`s and want to know if they are equal.”
* “I have an `Entity` (or `EntityName`) and want to get the entities that are related with a `RELATION_X` (e.g. API, Group, …).” (➡️  [`useRelatedEntities`](https://github.com/backstage/backstage/blob/9a2a925716bbe38c2cea753ec2ef0ee17e7a0263/plugins/api-docs/src/components/useRelatedEntities.ts))
* “I have a `UserEntity` (or `EntityName` of a user) and want to get their owned components/APIs/… (direct + indirect via groups).”
* “I have a `GroupEntity` (or `EntityName` of a group) and want to get their owned components/APIs/… (direct + indirect via all transitive children).”
* “I have a list of `Entity`s and want to know whether they are owned by a `User` or `Group`” <-- this one is primarily used by the catalog. All other uses probably don't already have a list of all entities to filter and need to download them anyway. But the logic would be replicated in the previous two.

## Possible Implementation

Questions are: 1. Where to put them? 2. How to name/structure them?

They could go into `catalog-model` but this would limit them to operate on an already existing list or entity.
They could go into `catalog-client` as functions returning Promises (not as react-hooks). Would also allow to use them in the backend.
They could go into a new `catalog-react` that provides common hooks. Makes it easy to consume it from react.

Having a common interface could also allow to handoff the filtering to the backend in the future (if needed).

## Context

This is needed by:
* The Catalog plugin
* The API-Docs plugin
* The orgs plugin
* Probably any kind of Squad/Team page that wants to apply plugins to a group of entities (ref https://github.com/backstage/backstage/issues/2752)

**Comment by Fox32** [comment]
> “I have an Entity (or EntityName) and want to get the entities that are related with a RELATION_X (e.g. API, Group, …).” (➡️ useRelatedEntities)
I would extend that requirement by allowing multiple or all relations that are on the entity.

> “I have a list of Entitys and want to know whether they are owned by a User or Group” 
I think in the long term we would get rid of this, as we should rewrite the catalog table to use server side filtering. Otherwise it won't scale well it bigger organizations.

I also played around with a [`useRecursiveRelatedEntities`](https://github.com/SDA-SE/backstage/blob/ca8f2bd710f86d0039c5cab7228493897b3d8b79/plugins/catalog/src/components/useRecursiveRelatedEntities.ts), but I think that would be quite a special case.

**Comment by dhenneke** [comment]
The calculation logic behind helpers will probably be defined by #3870. And regarding the package that houses the helpers, maybe we want different functions in different packages that may depend on one another (like a function/filter in the `catalog-client` that is used in some custom react-hook).

**Comment by freben** [comment]
Yep. We'll have to settle on some form of package structure for things like this. Say, if x = `plugin-catalog` for example, should we have the packages

- `x` (frontend plugin main code)
- `x-backend` (backend plugin main code)
- `x-common-react` (shared widgets and hooks and similar that both `x` and third party plugins can depend on)
- `x-common-node` (backend utilities and client etc)

... or something like that

**Comment by Fox32** [comment]
Something I would like to see in `catalog-common-react`: [`EntityRefLink`](https://github.com/backstage/backstage/blob/d5b92637bcc854b786d3237d50ba2544ddad728f/plugins/catalog/src/components/EntityRefLink/EntityRefLink.tsx).

**Comment by adamdmharvey** [comment]
@dhenneke Based on your initial report, the three linked functions have all moved, I believe, into `@backstage/plugin-catalog-react` and thus now are reusable.  I wonder if your root ask here is perhaps addressed now?  Thoughts or any suggestions you think?

**Comment by dhenneke** [comment]
Yes I agree. The general structure of packages is decided in [ADR 11](https://backstage.io/docs/architecture-decisions/adrs-adr011) and the proposed functions have been moved. Some of the suggested functions are still not implemented yet, but this can be done as a follow-up as soon as someone misses the functionality.
