### ISSUE TITLE
Catalog import from Azure DevOps broken (returns HTTP 404)

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#3973]
Import from Azure DevOps that was working before works no longer

## Expected Behavior

I was importing Azure DevOps git repo like https://dev.azure.com/org/project/_git/repository?path=%2Fsomefolder%2Fsomefile.yaml via register-component and it works so I expects the same when using catalog-import or at least return a proper error message what's wrong

## Current Behavior

When using /catalog-import and url like 'https://dev.azure.com/org/project/_git/repository?path=%2Fsomefolder%2Fsomefile.yaml' I am getting just "Failed to generate entity definitions. Received http response 404: Not Found". There is no error log just http 404 web server log:
{"type":"incomingRequest","message":"::ffff:... - - [08/Jan/2021:19:00:05 +0000] \"POST /api/catalog/analyze-location HTTP/1.1\" 404 - \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36\"","level":"info","service":"backstage"}

is this related?

## Possible Solution

well..no idea, why this stops working..

## Steps to Reproduce

Open /catalog-import
Put there url like 'https://dev.azure.com/org/project/_git/repository?path=%2Fsomefolder%2Fsomefile.yaml'

## Context

I had working integration with Azure DevOps in the previous version and I was able to add components via "/register-component" .

## Your Environment

Before we were using 0.4.3 version of backstage bundle, where there was plugin-register-component 0.2.6 and when using /register-component path it worked as expected.
Broken version: 2021/01/07, the above component was changed to plugin-catalog-import 0.3.3 which is I believe broken

- NodeJS Version (v12): v12.19.1
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04
- Browser Information: Chrome 87.0.4280.88

**Comment by freben** [comment]
@dtuite Do y'all have a moment to try to reproduce this?

**Comment by dtuite** [comment]
@freben we're can take a look. I'll raise it with the team on Monday.

**Comment by jvilimek** [comment]
Thanks @dtuite. Any progress, comments please?

**Comment by dtuite** [comment]
@jvilimek No progress yet. You can can see what we are working on on our [Open Source Development Board](https://github.com/orgs/RoadieHQ/projects/2). It is the next thing we will work on.

Just to set expectations on timing. It will probably be the end of the week before we get to look at this. I don't know how long it will take to complete the work. I will update here when we have progress to report.

**Comment by jvilimek** [comment]
Sure, thanks for info!

**Comment by mcalus3** [comment]
It's already resolved by https://github.com/backstage/backstage/pull/4014. Try on latest backstage build.

**Comment by jvilimek** [comment]
@mcalus3 thanks for info. Just few days ago we have upgraded to v2021-01-21. Version of @backstage/plugin-catalog-import is [^0.3.5](https://registry.yarnpkg.com/@backstage/plugin-catalog-import/-/plugin-catalog-import-0.3.5.tgz). And we still get the http 404 error.

This is what I see in logs:
```
{"type":"incomingRequest","message":"::ffff:... - - [03/Feb/2021:07:29:38 +0000] \"POST /api/catalog/analyze-location HTTP/1.1\" 404 - \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36\"","level":"info","service":"backstage"}
```

No other error details.


Not sure, if this is related, but this is what I see in logs from scaffolders:
```
{"type":"plugin","plugin":"catalog","message":"Failed item in location url:https://xxx.visualstudio.com/project/_git/repository?_a=contents&path=%2Ftools/backstage/atpservice-api.yaml, Error: Unable to read url, NotAllowedError: Reading from 'https://xxx.visualstudio.com/project/_git/repository?_a=contents&path=%2Ftools/backstage/atpservice-api.yaml' is not allowed\n    at generalError (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:856:55)\n    at UrlReaderProcessor.readLocation (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:2726:14)\n    at LocationReaders.handleLocation (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:948:31)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async LocationReaders.read (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:895:11)\n    at async HigherOrderOperations.refreshSingleLocation (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:818:26)\n    at async HigherOrderOperations.refreshAllLocations (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:807:9)\n    at async startRefresh (/home/user/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:748:9)","level":"warn","service":"backstage"}
```

**Comment by jvilimek** [comment]
I have just upgraded to 2021-02-01 version () and it seems, that the Azure DevOps YAML files are read. I have succeeded adding few (nearly empty) components, so I will close this issue as now it seems as a different error:
```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: xx-xx-v1
  description: XXXX API v1
spec:
  type: openapi
  lifecycle: production
  owner: someEmail@Oriflame.com
  definition:
    $text: https://xxxx.url.com/swagger-url-returning-json
```
throws an error: `Placeholder $text could not read location https://cc.oriflame.com/swagger/docs/v1, NotAllowedError: Reading from 'https://xxxx.url.com/swagger-url-returning-json' is not allowed` 

So I suppose something else changed, not the Azure DevOps integration.

**Comment by jvilimek** [comment]
Just for future reference, adding this
```yaml
  reading:
    allow:
      - host: xxxx.url.com
 ```
fixed the error. Some documentation can be found here: [packages/backend-common/config.d.ts](https://github.com/backstage/backstage/blob/master/packages/backend-common/config.d.ts) and [here](https://github.com/backstage/backstage/blob/master/app-config.yaml) is also a example, yet the new-ly generated app (via `npx @backstage/create-app`) does not contain this configuration. Also I was unable to find any documentation regarding this. Hope this issue/comments helps.
