### ISSUE TITLE
Cannot register new components  - No catalogInfoUrl returned from the scaffolder - Stage failed with error: Not Found Publish template

### ISSUE THREAD

**Issue by koolwithk** [backstage/backstage#4129]
Cannot register new components from any available templates(Golang Microservice, Documentation Template, etc) in backstage 

## Expected Behavior

- Should able to create Service, Website, Other component directly from Backstage 
- Should create Github repository

## Current Behavior

It's gives below error message "error: Stage failed with error: Not Found {"id":"7d458984-2b15-4d66-adca-efdbbf65f4d5","stage":"Publish template","timestamp":"2021-01-18T12:11:06.205Z"}"

AND

No catalogInfoUrl returned from the scaffolder

![image](https://user-images.githubusercontent.com/22337918/104918125-4fa5ff00-59ba-11eb-915d-d9778428c0e1.png)

**Backstage backend logs:**

2021-01-18T13:07:32.385Z catalog warn Failed item in location url:https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/documented-component.yaml, NotFoundError: Unable to read url, NotFoundError: https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/documented-component.yaml could not be read as https://api.github.com/repos/backstage/backstage/contents/plugins/techdocs-backend/examples/documented-component/documented-component.yaml?ref=master, 404 Not Found
    at Module.notFoundError (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/results.ts:40:12)
    at UrlReaderProcessor.readLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/processors/UrlReaderProcessor.ts:72:70)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async LocationReaders.handleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:142:13)
    at async LocationReaders.read (webpack-internal:///../../plugins/catalog-backend/src/ingestion/LocationReaders.ts:74:11)
    at async HigherOrderOperations.refreshSingleLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:159:26)
    at async HigherOrderOperations.refreshAllLocations (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:138:9)
    at async startRefresh (webpack-internal:///../../plugins/catalog-backend/src/util/runPeriodically.ts:42:9) type=plugin

## Possible Solution

Don't know, As workaround I'm creating the GitHub repository manually and adding catalog-info.yml file and then using Register Existing Component option 

## Steps to Reproduce

1. Create > Available Templates > Golang Microservice(or any default template) > Choose
2. Name , Description , all default , owner , Storepath=https://github.com/koolwithk/backstage-test,Access
3. Next Steps

## Context

- Installed backstage using https://backstage.io/docs/getting-started/running-backstage-locally
- Integrated with github OAuth Apps

## Your Environment

- Node (v14.15.4)
- NodeJS (v10.19.0)
- Ubuntu 20.04
- Chrome

**Comment by OrkoHunter** [comment]
Hey ! Could you pull the latest changes from the master branch if you are running a `git clone` version of Backstage? If you have a `@backstage/create-app` app, then please update the Software Template URL in your app config from

```
https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/documented-component.yaml
```

to

```
https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/catalog-info.yaml
```

That should fix it!

**Comment by koolwithk** [comment]
I have done git clone of master branch(head 4211198c3) and update the URL mention above in `app-config.yaml`  but still the same error **No catalogInfoUrl returned from the scaffolder AND Stage failed with error: Not Found Publish template**

Below are the command that i have run to configure backstage
```
git clone https://github.com:backstage/backstage.git
cd backstage
yarn install
yarn tsc
yarn build
```

I'm running backstage frontend and backend in 2 different terminal

```
#Terminal 1
cd /root/backstage
yarn start

#Terminial 2
cd /root/backstage/packages/backend
yarn start
```

but now i don't see that techdocs 404 error also now i'm able to see the **blank repository being created** on my github account.

**Comment by benjdlambert** [comment]
Can you try changing the store path to `koowithk/backstage-test` instead of having the `https://github.com` that support is introduced in #3900 which is not yet merged. :)

**Comment by koolwithk** [comment]
It's working with `koowithk/backstage-test` now :) Thank you!
I also tried this yesterday but it was not working I think that would be related to my browser cache.
