### ISSUE TITLE
You must configure at least one key in backend.auth.keys if permissions are enabled

### ISSUE THREAD

**Issue by lqlamTMA** [backstage/backstage#9498]
I had bump version of the plugins by command 'yarn backstage-cli versions:bump'
And then I tried to run the command 'yarn backstage-cli versions:bump' to start the backend. However, I have got error messaige: You must configure at least one key in backend.auth.keys if permissions are enabled

![image](https://user-images.githubusercontent.com/29789620/153767664-3fa4d936-77f1-4d85-adb8-499a1982804f.png)

**Comment by mtlewis** [comment]
Hi @iqlamTMA! This error usually appears because the permissions framework has been enabled (by setting `permission.enabled` to true in config), but backend-to-backend authentication (which is a prerequisite for using permissions) has not been set up. Does this match your local setup?

**Comment by delanni** [comment]
I'm also spinning around this issue. After a `verions:bump` call, I was presented with errors like: 
```
Backend failed to start up, Error: Config validation failed, Config should have required property 'keys' { missingProperty=keys } at /backend/auth
```

And I don't find a way to disable permissions, or any documentation that would straight point me to configuring permissions. 
I found this: https://backstage.io/docs/auth/auth-backend but this is empty. 

Can you recommend some documentation on how to adhere to the changed auth defaults after this was made different through a version bump.

**Comment by mtlewis** [comment]
Hi @delanni! The error message you're seeing is not related to permissions, but to [backend-to-backend authentication](https://backstage.io/docs/tutorials/backend-to-backend-auth). It looks like you may have some errant extra config hiding in your yaml file - do you by chance have the property `backend.auth` set? Today, this property should only be set if it contains a `keys` property with backend-to-backend auth keys.

If you do have `backend.auth` set in your config, you should be able to remove it - I think that will fix your issue.

**Comment by delanni** [comment]
I had to generate a new backstage project, to understand what's the desired configuration state / example, and copied parts to our existing application. 
Again, I was a bit lost for the lack of explicit configuration guidance in the documentation, but ultimately something small like this did the trick:
``` 
backend:
  auth:
    keys:
      - secret: ${BACKEND_SECRET}
```

**Comment by freben** [comment]
@mtlewis This should be fixed now, right? Can we close this now that the release is out?

**Comment by mtlewis** [comment]
The fix mentioned [here](https://github.com/backstage/backstage/issues/9498#issuecomment-1047135866) doesn't relate to the original issue really. @lqlamTMA were you able to resolve your original issue here?

**Comment by lqlamTMA** [comment]
Thanks @mtlewis .

**Comment by VGerris** [comment]
this is still an issue when following current docs and docker non staged.

**Comment by Jeroenvandepol** [comment]
Still present in the current install description. You can fix this by adding
backend:
  auth:
    keys:
      - secret: 'secret'
Tou your app-config yaml.

This needs te be a valid secret key offcourse, but it works for testing purposes.

**Comment by vinzscam** [comment]
> this is still an issue when following current docs and docker non staged.

this is not an issue but a strict requirement for enabling service-to-service auth

**Comment by omar-triguii** [comment]
how to get this secret please?

**Comment by Chilinot** [comment]
Creating a new project by following the guides, then going to the "building a docker image" guide as the next step results in this error.

Where do you get "a valid secret"?

**Comment by shadygrove** [comment]
@Chilinot I found this tip elsewhere for generating a secret... 

Create a random base64 value for the secret
```
node -p 'require("crypto").randomBytes(24).toString("base64")' 
```
Let's say you get "1Mf0/BAoWX0cOIm6lnpwz3/IF37OKyqz" from that.

Use that in the `backend.auth.secret`:  
```
  auth:
    keys:
      - secret: 1Mf0/BAoWX0cOIm6lnpwz3/IF37OKyqz
```

This worked for me running locally using Github Auth (that's a whole other story/issue/research/etc.)
